In [1]:
#Team Seals
#Heather, Mitchell, Ricky, Anh 

In [2]:
import numpy as np

In [18]:
class RawData(object):
    def __init__ (self, filename):
        self.filename = filename 
        self.headers = None
        self.data = None
    
    def read(self):
        got_header = False 
        for line in open(self.filename, 'r'):
         fields = line.strip().split(",")
         if not got_header:
            self.headers.np.append(fields[0])
            self.headers.np.append(fields[1])
            self.headers.np.append(fields[2]) 
            self.headers.np.append(fields[3])
            self.headers.np.append(fields[4])
            got_header = True
         else: 
            self.data[0].np.append(float(fields[0]))
            self.data[1].np.append(float(fields[1]))
            self.data[2].np.append(float(fields[2]))
            self.data[3].np.append(float(fields[3]))
            self.data[4].np.append(float(fields[4]))
    
    def getParVar(self):
        return self.headers
    
    def GetData(self):
        return self.data
    
    def GetCol(self, ColNum):
        return self.data[:,ColNum]
    
    def DataMatrix(self):
        data = np.genfromtxt('marine_data.csv', delimiter = ',')       
        x = data[1:, 1:]
        matrix = np.matrix([[x[0][0], 0, 0, 0, 0],[x[0][1], x[1][0], 0, 0, 0], [0, x[1][1], x[2][0], 0, 0], [0, 0, x[2][1],x[3][0],0], [0, 0, 0, x[3][1],x[4][0]]])
        zeros = np.matrix(x[:, 2])
        tzero = np.transpose(zeros)
        BioMass = np.linalg.solve(matrix,tzero)
        print tzero   
        print matrix
        print BioMass
        return BioMass
    

In [19]:
RD = RawData('marine_data.csv')
RD.DataMatrix()


[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 0.]]
[[  5.00220000e-02   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [ -2.45940000e+01   1.35200000e-01   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00  -3.78400000e+00   2.02500000e+00   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00  -1.20000000e+01   8.00000000e+01
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00  -2.85714000e+02
    7.20000000e+00]]
[[  1.99912039e+01]
 [  3.65135849e+03]
 [  6.82456322e+03]
 [  1.02373448e+03]
 [  4.06243436e+04]]


matrix([[  1.99912039e+01],
        [  3.65135849e+03],
        [  6.82456322e+03],
        [  1.02373448e+03],
        [  4.06243436e+04]])

In [16]:
a = RD.DataMatrix()

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 0.]]
[[  5.00220000e-02   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [ -2.45940000e+01   1.35200000e-01   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00  -3.78400000e+00   2.02500000e+00   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00  -1.20000000e+01   8.00000000e+01
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00  -2.85714000e+02
    7.20000000e+00]]
[[  1.99912039e+01]
 [  3.65135849e+03]
 [  6.82456322e+03]
 [  1.02373448e+03]
 [  4.06243436e+04]]


In [17]:
print a[0][0]

[[ 19.99120387]]


In [16]:
print (a[:,0]*a[:,1]) - (a[:,2]) - (a[

[  5.00220000e-02   1.35200000e-01   2.02500000e+00   8.00000000e+01
   7.20000000e+00]


[ 0.  0.  0.  0.  0.]


In [11]:
print a[;0]*a[;1]

[  3.27600000e-02   2.06440000e-01   9.30636960e+01   0.00000000e+00]
